spring.application.name=management

spring.datasource.url=jdbc:mysql://mysql-18dc8603-clinicamedico.f.aivencloud.com:16390/db_medical?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_-D3w_oeylud5Y56sGLD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
